[tool.poetry]
name = "ml-classifier-app-new"
version = "0.1.0"
description = ""
authors = ["abhirup-de <creative.abhirup@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
